#########################
### Nome da aplicação ###
#########################
spring.application.name=catalogo

######################################################################
### Configuração do Console H2 (Acesse: localhost:8080/h2-console) ###
######################################################################
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:catalogodb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

######################################################################
### Configuração do PostreSQL                                      ###
######################################################################
# Configurações de Conexão
spring.datasource.url=jdbc:postgresql://localhost:5433/catalogo_db
spring.datasource.username=postgres
spring.datasource.password=sua_senha_aqui

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect